// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using ProjectTest.Model;

#nullable disable

namespace ProjectTest.Data
{
    public partial class DataContext : DbContext
    {
        public DataContext()
        {
        }

        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MsPromoType> MsPromoType { get; set; }
        public virtual DbSet<MsUsers> MsUsers { get; set; }
        public virtual DbSet<TrPromotion> TrPromotion { get; set; }
        public virtual DbSet<TrStores> TrStores { get; set; }
    }
}