// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectTest.Model
{
    public partial class MsPromoType
    {
        public int Id { get; set; }
        public string PromoName { get; set; }
        public bool IsActive { get; set; }
    }
}