// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectTest.Model
{
    public partial class TrPromotion
    {
        public int Id { get; set; }
        public string PromoId { get; set; }
        public string PromoType { get; set; }
        public int ValueType { get; set; }
        public string PromoDescription { get; set; }
        public DateTime PromoStart { get; set; }
        public DateTime PromoEnd { get; set; }
        public DateTime Created { get; set; }
        public string CreatedBy { get; set; }
        public DateTime Modified { get; set; }
        public string ModifiedBy { get; set; }
    }
}