// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectTest.Model
{
    public partial class TrStores
    {
        public int Id { get; set; }
        public string PromoId { get; set; }
        public string Store { get; set; }
        public string StoreName { get; set; }
    }
}